paths:
  data: data/jokes_clean.txt
  models_checkpoints: ./artifacts/checpoints/models/
  tokenizers_checkpoints: ./artifacts/checpoints/tokenizers/
  
env:
  seed: 42
  device: cuda:2

model:
  type: transformer
  name: Transformer_v03
  model_params:
    vocab_size: 5000
    hidden_size: 384
    num_layers: 6
    num_heads: 6
    dropout: 0.15
    model_max_length: 128

  tokenizer_params:
    special_tokens: ["[PAD]", "[UNK]", "[BOS]", "[EOS]"]

train_params:
  num_epochs: 11
  batch_size: 512
  num_workers: 2
  lr: 5e-4
  weight_decay: 1e-2
  gamma: 0.75
  scheduler_step: 2
  loss_logging_step: 500
  gradient_clip: 1.0